export const GAME_WIDTH = 960
export const GAME_HEIGHT = 460
export const GROUND_Y = 362
export const WIN_SCORE = 900
export const MAX_LEVEL = 8
export const HINTS_PER_GAME = 2

export const playerConfig = {
  width: 46,
  height: 62,
  speed: 5.2,
}

export const goodObjects = [
  {
    type: 'leaf',
    label: 'Hoja verde',
    points: 10,
    color: '#86efac',
    ods: 13,
    message: 'Bien hecho. Esta accion ayuda al ODS 13.',
  },
  {
    type: 'bottle',
    label: 'Botella reciclable',
    points: 12,
    color: '#38bdf8',
    ods: 12,
    message: 'Reciclar ayuda al ODS 12.',
  },
  {
    type: 'water',
    label: 'Gota de agua',
    points: 14,
    color: '#22d3ee',
    ods: 6,
    message: 'Cuidar el agua ayuda al ODS 6.',
  },
  {
    type: 'tree',
    label: 'Arbol',
    points: 16,
    color: '#22c55e',
    ods: 15,
    message: 'Plantar arboles ayuda al ODS 15.',
  },
  {
    type: 'bin',
    label: 'Contenedor',
    points: 18,
    color: '#84cc16',
    ods: 11,
    message: 'Una ciudad limpia ayuda al ODS 11.',
  },
]

export const badObjects = [
  {
    type: 'smoke',
    label: 'Humo contaminante',
    damage: 1,
    color: '#64748b',
    ods: 13,
    message: 'Cuidado, ese humo contamina. Intenta evitarlo.',
  },
  {
    type: 'barrel',
    label: 'Barril contaminante',
    damage: 1,
    color: '#f97316',
    ods: 12,
    message: 'Cuidado, ese objeto contamina. Intenta evitarlo.',
  },
  {
    type: 'fire',
    label: 'Fuego',
    damage: 1,
    color: '#ef4444',
    ods: 15,
    message: 'Evita el fuego para cuidar los bosques.',
  },
  {
    type: 'trash',
    label: 'Basura peligrosa',
    damage: 1,
    color: '#a855f7',
    ods: 11,
    message: 'Evita la basura peligrosa. Cuida tu ciudad.',
  },
  {
    type: 'spill',
    label: 'Derrame quimico',
    damage: 1,
    color: '#facc15',
    ods: 6,
    message: 'Evita derrames para cuidar el agua.',
  },
]

export const gameMissions = [
  {
    id: 'tutorial-bottles',
    level: 0,
    title: 'Tutorial: recoge 2 botellas',
    shortTitle: 'Tutorial',
    type: 'collect',
    objectType: 'bottle',
    target: 2,
    ods: 12,
    message: 'Muy bien. Ya sabes recolectar.',
    needsQuestion: false,
  },
  {
    id: 'bottles',
    level: 1,
    title: 'Recoge 3 botellas reciclables',
    shortTitle: '3 botellas',
    type: 'collect',
    objectType: 'bottle',
    target: 3,
    ods: 12,
    message: 'Reciclar ayuda al ODS 12.',
    needsQuestion: false,
  },
  {
    id: 'water',
    level: 2,
    title: 'Cuida 2 gotas de agua',
    shortTitle: '2 gotas',
    type: 'collect',
    objectType: 'water',
    target: 2,
    ods: 6,
    message: 'Cuidar el agua ayuda al ODS 6.',
    needsQuestion: false,
  },
  {
    id: 'tree',
    level: 3,
    title: 'Planta 1 arbol',
    shortTitle: '1 arbol',
    type: 'collect',
    objectType: 'tree',
    target: 1,
    ods: 15,
    message: 'Plantar arboles ayuda al ODS 15.',
    needsQuestion: false,
  },
  {
    id: 'avoid-smoke',
    level: 4,
    title: 'Evita 2 humos contaminantes',
    shortTitle: 'Evita humo',
    type: 'avoid',
    objectType: 'smoke',
    target: 2,
    ods: 13,
    message: 'Evitar contaminacion ayuda al ODS 13.',
    needsQuestion: false,
  },
  {
    id: 'clean-city',
    level: 5,
    title: 'Limpia la ciudad con 3 contenedores',
    shortTitle: '3 contenedores',
    type: 'collect',
    objectType: 'bin',
    target: 3,
    ods: 11,
    message: 'Una ciudad limpia ayuda al ODS 11.',
    needsQuestion: false,
  },
  {
    id: 'climate-leaves',
    level: 6,
    title: 'Recolecta 4 hojas verdes',
    shortTitle: '4 hojas',
    type: 'collect',
    objectType: 'leaf',
    target: 4,
    ods: 13,
    message: 'Cada accion verde suma al clima.',
    needsQuestion: false,
  },
]

export const initialStats = {
  score: 0,
  lives: 4,
  level: 0,
  collected: 0,
  target: gameMissions[0].target,
  missionIndex: 0,
  missionProgress: 0,
  correctAnswers: 0,
  hintsLeft: HINTS_PER_GAME,
  round: 1,
  tutorialDone: false,
  status: 'idle',
}
